services:
  mitmproxy:
    image: mitmproxy/mitmproxy
    mem_limit: 512m
    memswap_limit: 1g
    oom_score_adj: 1000
    ports:
      - "8084:8080"  # mitmproxy proxy port
      - "8085:8081"  # mitmweb interface port
    volumes:
      - ./mitm_logs:/logs
      - ./mitm_certs:/home/mitmproxy/.mitmproxy
    command: mitmweb --web-host 0.0.0.0 --set web_password="password123" --set flow_detail=2 -w /logs/arda_traffic.flow
    restart: unless-stopped

networks:
  default:
    name: arda-mitmproxy 